### ISSUE TITLE
debootstrap is used kinda improperly

### ISSUE THREAD

**Issue by Maccraft123** [austin987/crawfishos#1]
According to manpage of debootstrap, --foreign option should be used to bootstrap a debian installation to target, but it looks like it was accidentally left out in commit https://github.com/austin987/crawfishos/commit/62f8988ff48bdfeb2135e02bcb2b350163a1d586

IIRC this fails with systems that lack binfmt_misc support in their kernel

**Comment by austin987** [comment]
So I tried this, and it fails on both my desktop and with github actions (and at least my local kernel supports binfmt_misc).

The build fails somewhat cryptically when trying to chroot:
```
+ chroot /PrawnOS/tmp.s6dzBgBu4W passwd -d root
passwd: Cannot determine your user name.
```

reverting --foreign fixes it. See https://github.com/austin987/PrawnOS/actions/runs/700655926 versus https://github.com/austin987/PrawnOS/actions/runs/700807091

I'm not sure if another option is required or if it's a bug, but IMO it's not worth fixing, at least for now, since it's not broken..

**Comment by Maccraft123** [comment]
weird

**Comment by Maccraft123** [comment]
And now they deprecated it in 1:5.2+dfsg-6
http://metadata.ftp-master.debian.org/changelogs/main/q/qemu/unstable_changelog

**Comment by austin987** [comment]
qemu-debootstrap isn't used anymore..
